test:
	python interactive_runner.py python local_testing_tool.py 0 -- ./solve.py
	python interactive_runner.py python local_testing_tool.py 1 -- ./solve.py
	python interactive_runner.py python local_testing_tool.py 2 -- ./solve.py

.PHONY: test

