test:
	python3 interactive_runner.py python3 local_testing_tool.py 0 -- ./solve.py | batcat
	#python3 interactive_runner.py python3 local_testing_tool.py 1 -- ./solve.py
	#python3 interactive_runner.py python3 local_testing_tool.py 2 -- ./solve.py

.PHONY: test

